id: A325CF755
title: CI_Verses 21-31
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:28:40.400832
  last_modified_at: 2022-03-01 23:28:40.400837
